### ISSUE TITLE
Is it worth thinking about using rappdirs for this?

### ISSUE THREAD

**Issue by adamhsparks** [AndySouth/climcropr#1]
I'm reading your comments about gunzip deleting files, etc. and was thinking that perhaps it's useful to consider using [_rappdirs_](https://github.com/r-lib/rappdirs) for storing these data for repeated use?

If so I can work on it and submit a pull request if you'd like?

I did this with my [_getCRUCLdata_](https://github.com/ropensci/getCRUCLdata) package to save the user repeated downloads.

**Comment by andysouth** [comment]
Thanks Adam,
That looks interesting. I'm still experimenting with what I want to do at
the moment, but may get back to you on this, I wasn't aware of rappdirs.
Also your CRU package looks very cool.
I'll be in touch.
Andy

**Comment by adamhsparks** [comment]
No worries. I was thinking that this might be a good use case. I don't know what you envision yet, but I was thinking that a user might want to compare different climate or weather data sets for the same crop so having the MIRCA crop data cached locally could be useful or even just rerunning the same code and not downloading over and over.

cheers!

**Comment by andysouth** [comment]
You're right. In the short term I've just been trying to get a comparison
working for a few select crops. I was wondering whether to just store all
the data in the package, but may take up too much space for cran and good
to have the option to download other layers too. So if you are to happy to
submit a PR then I'll be happy to receive !

**Comment by adamhsparks** [comment]
PR sent.

I've done my best to write some tests and eliminate messages when checking the package.

**Comment by andysouth** [comment]
Hi Adam,
The code looks really great, great to have a test too. Thanks.

A glitch when I try to run it, is this a problem with my setup ?
Andy

plot(get_mirca('maize'))

Downloading requested MIRCA file.
 
Error in value[[3L]](cond) : 
The file download has failed.
   
Please start the download again.
In addition: Warning message:
In dir.create(cache_dir) :
  cannot create dir 'C:\Users\andy\AppData\Roaming\climcropr\climcropr', reason 'No such file or directory'

**Comment by adamhsparks** [comment]
Hi Andy,
Something isn't right yet. Let me look into it.

**Comment by adamhsparks** [comment]
Hi Andy,
New pull request sent. Thanks for finding this. I don't have ready access to a Windows machine, so I sourced one and sussed out the issue.

I think it's fixed in the newest pull request.

I've also expanded the tests for the caching function to check that it doesn't create a directory if caching is FALSE

**Comment by adamhsparks** [comment]
Oh, btw, the function `get_mirca()` will automatically plot the resulting MIRCA2000 file by default unless `plot = FALSE`.

**Comment by adamhsparks** [comment]
Realised just now that I never closed this after submitting the PR that's been merged.

Closing now.

**Comment by andysouth** [comment]
Super, thanks for your input Adam.
I'll be doing some more on this in a few weeks time, will send you an
update then.
